### ISSUE TITLE
It is inconvenient that states have to be hashable

### ISSUE THREAD

**Issue by Freakwill** [simpleai-team/simpleai#73]
It is inconvenient that states have to be hashable. Why not remove the restriction? OR define apis converting state to its hashable version (e.g. self.state_representation(state)) automatically, the users could focus on the raw states.

**Comment by fisadev** [comment]
Hi!

It's required to be able to use graph_search without it becoming super slow, as it needs to check if the state was previously seen. Being hashables, we can use a set and the time to the check becomes trivial  (O(1)), while if they weren't hashable then the time to check in the closed list would increase linearly with the number of visited states, and each lookup would take more and more time.

It also has another less obvious benefit: most people using this lib to learn AI don't have too much experience in python, and don't immediately understand the dangers of having a mutable states and doing mutations in the result() method. Doing this would lead to unknowingly altering the states of previous nodes, something that will surely bite most newcomers. Hashable types are usually immutable types, which automatically prevent this problem.

Having to define a method that converts states to hashable representations is an interesting idea, but I see this problem: if we make that mandatory, it ads an extra and slightly obscure thing to do, which isn't AI related or obvious, that we would need to explain to the students or doc readers.
While not making it mandatory (default = using state itself) creates the chance of people using mutable states, not defining it, and doing changes to the parent state in result(), something that will bite most people.

So for now, we prefer this approach. It has the problem of requiring hashable types, which can be annoying, but both prevents the unexpected state mutations and doesn't require extra methods to be defined in your problem.
