### ISSUE TITLE
Possible security issues on line 271

### ISSUE THREAD

**Issue by K-Dub1234** [simpleai-team/simpleai#75]
on line 271 (`add_branch`), I propose a encrypted `return branch`, by adding a randomized value before and after the "branch" or, if the returned value is a number, I recommend using a lock and key.
         `

**Comment by fisadev** [comment]
I don't understand what you are proposing, at all. `add_branch` adds a branch to a decision tree, based on the combination of attribute and value that better splits the subset of the train data up to that point (reducing entropy on the split). 

There's no need for it to be "secure", it's acting on a subset of the dataset used to train the decision tree. Obfuscating the data on the node won't add any level of security to it, as the data is still available in the train dataset. And the whole point of building a decision tree, is to construct a clear graph of decisions that tell you how to make predictions based on the values of the inputs, hiding those decisions isn't adding "security", it would be hiding the result itself that you wanted to obtain.

Adding randomized values before and after the branch how? As nodes in the tree? What benefit would that have?
Using a lock and key in the tree node? How? To achieve what in particular?
